#!/usr/bin/env bash 

set -e -o pipefail

if [ -z "$BACKUP_DIR" ]; then
    echo "BACKUP_DIR not set"
    exit 128
fi

MYCONN="--user=${MYSQL_USER-root} --password=${MYSQL_PASS-${MYSQL_ENV_MYSQL_ROOT_PASSWORD}} --host=${MYSQL_HOST-${MYSQL_PORT_3306_TCP_ADDR-localhost}} --port=${MYSQL_PORT_3306_TCP_PORT-${MYSQL_PORT-3306}}"
MYSQL="mysql ${MYCONN}"
GZIP="gzip --fast"
MYDUMP="mysqldump ${MYCONN}"
BACKUP_PATH="${BACKUP_DIR}/$(date +%Y%m%d%H%M)"
DATABASES=$($MYSQL -rs -e "SHOW DATABASES" | grep -v -E '(information_schema|performance_schema)')
RETENTION_DAYS=${RETENTION_DAYS-14}

# Perform the backup
mkdir -p "$BACKUP_PATH"
echo -n "Dumping..."
for DB in $DATABASES; do
    echo -n " $DB"
    $MYDUMP --opt --single-transaction --flush-logs --events --databases ${DB} | $GZIP > "${BACKUP_PATH}/${DB}.sql.gz"
done
echo ". Done."

# Delete expired backups
echo -n "Cleanup... "
find ${BACKUP_DIR} -name "*.sql.gz" -mtime +$RETENTION_DAYS -exec rm -f {} \; 
find ${BACKUP_DIR} -type d -empty -delete
echo "Done."
