#!/usr/bin/env bash 

set -e -o pipefail

DATABASES=$@

MYCONN="--user=${MYSQL_USER-root} --password=${MYSQL_PASS-${MYSQL_ENV_MYSQL_ROOT_PASSWORD}} --host=${MYSQL_HOST-${MYSQL_PORT_3306_TCP_ADDR-localhost}} --port=${MYSQL_PORT_3306_TCP_PORT-${MYSQL_PORT-3306}}"
MYSQL="mysql ${MYCONN}"

# Convert to Innodb
for DB in $DATABASES; do
    TO_CONVERT=$(echo "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = \"$DB\" and engine = 'MyISAM';" | $MYSQL)
    echo -n "Converting $TO_CONVERT in $DB..."
    echo $TO_CONVERT | awk '!/^Tables_in_/ {print "ALTER TABLE `"$0"` ENGINE = InnoDB;"}' | $MYSQL
    echo ". Done."
done

echo "All done."
