#!/usr/bin/env bash

set -e

genpasswd() {
    export LC_CTYPE=C  # Quiet tr warnings
    local l=$1
    [ "$l" == "" ] && l=16
    strings < /dev/urandom | tr -dc A-Za-z0-9_ | head -c ${l}
}

if [ "$1" == '--no-create-database' ]; then
    shift;
    CREATE_DB=false
else
    CREATE_DB=true
fi

if [ -z "$1" ]; then
    echo "User not specified"
    exit 128
fi

if [ -z "${DATABASE_HOST}" ]; then
    echo -n "=> Using Docker Links for configuration "
    DATABASE_PASS=$MARIADB_ENV_MYSQL_ROOT_PASSWORD
    DATABASE_USER=root
    DATABASE_HOST=$MARIADB_PORT_3306_TCP_ADDR
    DATABASE_PORT=$MARIADB_PORT_3306_TCP_PORT
    echo "mysql://${DATABASE_HOST}:$DATABASE_PORT"
else
    echo -n  "=> Using variables for configuration "
    DATABASE_HOST=${DATABASE_HOST-localhost}
    DATABASE_PORT=${DATABASE_PORT-3306}
    echo "mysql://${DATABASE_HOST}:$DATABASE_PORT"
fi

USER=$1
PASS=${2-$(genpasswd 8)}
MYSQL="mysql --host=${DATABASE_HOST} --port=${DATABASE_PORT} --user=${DATABASE_USER} --password=${DATABASE_PASS}"

if [ "$CREATE_DB" == 'true' ]; then
    echo ">>> Creating user and database: $USER..."
else
    echo ">>> Creating user: $USER..."
fi

if [ "$CREATE_DB" == 'true' ]; then
    echo "CREATE DATABASE IF NOT EXISTS ${$USER};" | $MYSQL
fi
echo "GRANT ALL ON ${USER}.* to ${USER}@'%' IDENTIFIED BY '$PASS';" | $MYSQL
echo "Created: ${USER} / ${PASS}"
echo "FLUSH PRIVILEGES;" | $MYSQL
echo ">>> Finished."
